ALTER TABLE orders ADD COLUMN review_token VARCHAR(36) UNIQUE DEFAULT NULL AFTER mp_status;
ALTER TABLE orders ADD COLUMN reviewed BOOLEAN NOT NULL DEFAULT FALSE AFTER review_token;
ALTER TABLE reviews ADD COLUMN order_id INT DEFAULT NULL AFTER id;
ALTER TABLE reviews ADD COLUMN customer_phone VARCHAR(50) DEFAULT NULL AFTER customer_name;
