export const rubroSettings = {
  fiambres: {
    rubro: 'fiambres',
    store_name: 'Fiambres',
    rubro_label: 'Fiambrería',
    subtitle: 'Productos frescos · Pedidos por WhatsApp',
    promo: '🎉 Pedidos de lunes a sábado — Consultá disponibilidad y envío',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '25000',
    shipping_cost: '2000',
    info_hours: 'Lunes a Sábado · 8:00–13:00 / 17:00–21:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia MP',
    mp_alias: 'FIAMBRES.MP',
    mp_cvu: '0000003100000000000001',
    mp_holder: 'María López',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000001',
    bank_alias: 'FIAMBRES.BP',
    bank_holder: 'María López',
    theme_preset: 'fiambres',
  },
  ferreteria: {
    rubro: 'ferreteria',
    store_name: 'Ferretería',
    rubro_label: 'Ferretería',
    subtitle: 'Herramientas profesionales · Pedidos por WhatsApp',
    promo: '🔧 Envíos a toda la zona — Consultá precios mayoristas',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '50000',
    shipping_cost: '3000',
    info_hours: 'Lunes a Viernes · 8:00–18:00 / Sábados 8:00–13:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia MP · Tarjeta',
    mp_alias: 'FERRETERIA.MP',
    mp_cvu: '0000003100000000000002',
    mp_holder: 'Carlos Herrera',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000002',
    bank_alias: 'FERRETERIA.BP',
    bank_holder: 'Carlos Herrera',
    theme_preset: 'ferreteria',
  },
  herramientas: {
    rubro: 'herramientas',
    store_name: 'Herramientas',
    rubro_label: 'Herramientas',
    subtitle: 'Herramientas profesionales · Pedidos por WhatsApp',
    promo: '🔧 Envíos a toda la zona — Consultá precios mayoristas',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '50000',
    shipping_cost: '3000',
    info_hours: 'Lunes a Viernes · 8:00–18:00 / Sábados 8:00–13:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia MP · Tarjeta',
    mp_alias: 'HERRAMIENTAS.MP',
    mp_cvu: '0000003100000000000002',
    mp_holder: 'Carlos Herrera',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000002',
    bank_alias: 'HERRAMIENTAS.BP',
    bank_holder: 'Carlos Herrera',
    theme_preset: 'herramientas',
  },
  verduleria: {
    rubro: 'verduleria',
    store_name: 'Verdulería',
    rubro_label: 'Verdulería',
    subtitle: 'Frutas y verduras frescas · Pedidos por WhatsApp',
    promo: '🥬 Productos de estación — Consultá disponibilidad y envío',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '15000',
    shipping_cost: '1500',
    info_hours: 'Lunes a Sábados · 7:00–20:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia MP',
    mp_alias: 'VERDULERIA.MP',
    mp_cvu: '0000003100000000000003',
    mp_holder: 'Ana Martínez',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000003',
    bank_alias: 'VERDULERIA.BP',
    bank_holder: 'Ana Martínez',
    theme_preset: 'verduleria',
  },
  carniceria: {
    rubro: 'carniceria',
    store_name: 'Carnicería',
    rubro_label: 'Carnicería',
    subtitle: 'Carnes frescas · Cortes seleccionados · Pedidos por WhatsApp',
    promo: '🥩 Carnes de primera calidad — Consultá disponibilidad y envío',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '30000',
    shipping_cost: '2500',
    info_hours: 'Lunes a Sábado · 8:00–14:00 / 17:00–20:30',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia · Tarjeta',
    mp_alias: 'CARNICERIA.MP',
    mp_cvu: '0000003100000000000004',
    mp_holder: 'Pedro González',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000004',
    bank_alias: 'CARNICERIA.BP',
    bank_holder: 'Pedro González',
    theme_preset: 'carniceria',
  },
  panaderia: {
    rubro: 'panaderia',
    store_name: 'Panadería',
    rubro_label: 'Panadería',
    subtitle: 'Pan artesanal · Facturas · Pastelería · Pedidos por WhatsApp',
    promo: '🥐 Horneamos todos los días — Pedí con anticipación',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '15000',
    shipping_cost: '1500',
    info_hours: 'Lunes a Domingo · 7:00–21:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia',
    mp_alias: 'PANADERIA.MP',
    mp_cvu: '0000003100000000000005',
    mp_holder: 'Laura Rodríguez',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000005',
    bank_alias: 'PANADERIA.BP',
    bank_holder: 'Laura Rodríguez',
    theme_preset: 'panaderia',
  },
  libreria: {
    rubro: 'libreria',
    store_name: 'Librería',
    rubro_label: 'Librería',
    subtitle: 'Útiles escolares · Papelería · Libros · Pedidos por WhatsApp',
    promo: '📚 Todo para tu estudio y oficina — Consultá precios mayoristas',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '20000',
    shipping_cost: '1800',
    info_hours: 'Lunes a Viernes · 9:00–19:00 / Sábados 9:00–13:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia · Tarjeta',
    mp_alias: 'LIBRERIA.MP',
    mp_cvu: '0000003100000000000006',
    mp_holder: 'Sofía García',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000006',
    bank_alias: 'LIBRERIA.BP',
    bank_holder: 'Sofía García',
    theme_preset: 'libreria',
  },
  indumentaria: {
    rubro: 'indumentaria',
    store_name: 'Indumentaria',
    rubro_label: 'Indumentaria',
    subtitle: 'Ropa y accesorios · Moda urbana · Pedidos por WhatsApp',
    promo: '👕 Las últimas tendencias — Envíos a todo el país',
    whatsapp: '542920286288',
    currency: 'ARS',
    shipping_free: '40000',
    shipping_cost: '3000',
    info_hours: 'Lunes a Viernes · 9:00–20:00 / Sábados 10:00–14:00',
    info_phone: '',
    info_delivery: 'Consultá disponibilidad por zona',
    info_payment: 'Efectivo · Transferencia · Tarjeta',
    mp_alias: '',
    mp_alias: 'INDUMENTARIA.MP',
    mp_cvu: '0000003100000000000007',
    mp_holder: 'Martín Díaz',
    bank_entity: 'Banco Patagonia',
    bank_cbu: '0340000500000000000007',
    bank_alias: 'INDUMENTARIA.BP',
    bank_holder: 'Martín Díaz',
    theme_preset: 'indumentaria',
  },
};

export const seeds = {
  fiambres: {
    categories: [
      { name: 'Fiambres', slug: 'fiambres', icon: '🥩', sort_order: 1 },
      { name: 'Milanesas', slug: 'milanesas', icon: '🍗', sort_order: 2 },
      { name: 'Panadería', slug: 'panaderia', icon: '🍞', sort_order: 3 },
      { name: 'Pizzas', slug: 'pizzas', icon: '🍕', sort_order: 4 },
      { name: 'Sanguches', slug: 'sanguches', icon: '🥪', sort_order: 5 },
    ],
    products: [
      { cat: 'fiambres', name: 'Queso Sardo', price: 2300, unit: '100g', emoji: '🧀', desc: 'Queso duro de pasta cocida, ideal para rallar y fondues. Sabor intenso y textura firme.' },
      { cat: 'fiambres', name: 'Queso Cremoso Cremón', price: 1600, unit: '100g', emoji: '🧀', desc: 'Queso untable cremoso, suave y versátil. Perfecto para sándwiches y picadas.' },
      { cat: 'fiambres', name: 'Jamón Cocido', price: 2400, unit: '100g', emoji: '🍖', desc: 'Jamón cocido natural, jugoso y de calidad premium. Ideal para sándwiches y tablas.' },
      { cat: 'fiambres', name: 'Salame Milán Premium', price: 2900, unit: '100g', emoji: '🥓', desc: 'Salame tipo Milán elaborado artesanalmente con especias seleccionadas.' },
      { cat: 'fiambres', name: 'Jamón Crudo', price: 4400, unit: '100g', emoji: '🍖', desc: 'Jamón crudo curado, de sabor profundo y textura delicada. Ideal para pizzas y picadas.' },
      { cat: 'fiambres', name: 'Panceta Ahumada', price: 3900, unit: '100g', emoji: '🥓', desc: 'Panceta ahumada con leña de quebracho. Crujiente y llena de sabor.' },
      { cat: 'fiambres', name: 'Lomo Ahumado', price: 3500, unit: '100g', emoji: '🥩', desc: 'Lomo de cerdo ahumado, jugoso y tierno. Ideal para sándwiches gourmet.' },
      { cat: 'milanesas', name: 'Milanesa de Pollo (pechuga)', price: 10900, unit: 'kg', emoji: '🍗', desc: 'Milanesas de pechuga de pollo, empanadas Artesanalmente. Listas para freír u hornear.' },
      { cat: 'milanesas', name: 'Milanesa de Nalga', price: 23900, unit: 'kg', emoji: '🥩', desc: 'Milanesas de nalga de primera calidad, carne tierna y sabrosa.' },
      { cat: 'panaderia', name: 'Pan Lactal Chico', price: 4500, unit: 'unidad', emoji: '🍞', desc: 'Pan lactal artesanal, esponjoso y fresco. Horneado diariamente.' },
      { cat: 'pizzas', name: 'Pizza Muzzarella', price: 6500, unit: 'unidad', emoji: '🍕', desc: 'Pizza tradicional con muzzarella, salsa de tomate casera y orégano.' },
      { cat: 'pizzas', name: 'Pizza Jamón Crudo', price: 8500, unit: 'unidad', emoji: '🍕', desc: 'Pizza con jamón crudo, muzzarella y rúcula fresca. Una delicia única.' },
      { cat: 'sanguches', name: 'Jamón y Queso', price: 5000, unit: 'x3 u.', emoji: '🥪', desc: 'Sanguches de jamón cocido y queso cremoso en pan lactal fresco. x3 unidades.' },
    ],
    combos: [
      { name: 'Queso Barra + Jamón', desc: '1kg de Queso Barra + 1kg de Jamón Cocido', emoji: '🧀🍖', price: 29500, products: ['Queso Sardo', 'Jamón Cocido'] },
      { name: 'Picada x4 personas', desc: 'Salame + Jamón + Queso + Mortadela (1kg total)', emoji: '🫒', price: 22900, products: ['Salame Milán Premium', 'Jamón Crudo', 'Queso Cremoso Cremón', 'Lomo Ahumado'] },
    ],
  },
  ferreteria: {
    categories: [
      { name: 'Herramientas Manuales', slug: 'hand-tools', icon: '🔧', sort_order: 1 },
      { name: 'Herramientas Eléctricas', slug: 'power-tools', icon: '⚡', sort_order: 2 },
      { name: 'Pinturería', slug: 'paint', icon: '🎨', sort_order: 3 },
      { name: 'Plomería', slug: 'plumbing', icon: '🔩', sort_order: 4 },
      { name: 'Fijaciones', slug: 'hardware', icon: '⚙️', sort_order: 5 },
      { name: 'Jardinería', slug: 'garden', icon: '🌿', sort_order: 6 },
    ],
    products: [
      { cat: 'hand-tools', name: 'Martillo de Carpintero 500g', price: 8900, unit: 'unidad', emoji: '🔨', desc: 'Martillo profesional con mango de fibra y cabeza forjada. Ideal para carpintería y construcción.' },
      { cat: 'hand-tools', name: 'Martillo de Uña 300g', price: 6500, unit: 'unidad', emoji: '🔨', desc: 'Martillo de uña liviano, perfecto para tareas de precisión y extracción de clavos.' },
      { cat: 'hand-tools', name: 'Destornillador Plano 6mm', price: 3500, unit: 'unidad', emoji: '🪛', desc: 'Destornillador plano con mango ergonómico antideslizante y punta magnética.' },
      { cat: 'hand-tools', name: 'Destornillador Phillips #2', price: 3500, unit: 'unidad', emoji: '🪛', desc: 'Destornillador Phillips de punta magnética con mango bi-material antideslizante.' },
      { cat: 'hand-tools', name: 'Pinza Universal 8"', price: 7200, unit: 'unidad', emoji: '🔧', desc: 'Pinza universal de acero al carbono con mango forrado. Corte y agarre precisos.' },
      { cat: 'hand-tools', name: 'Pinza de Corte 7"', price: 6800, unit: 'unidad', emoji: '✂️', desc: 'Pinza de corte diagonal para cables y alambres. Acero templado con filo preciso.' },
      { cat: 'hand-tools', name: 'Cinta Métrica 5m', price: 4800, unit: 'unidad', emoji: '📏', desc: 'Cinta métrica retráctil de 5 metros con cierre magnético y gancho de extremo.' },
      { cat: 'hand-tools', name: 'Cinta Métrica 8m', price: 7200, unit: 'unidad', emoji: '📏', desc: 'Cinta métrica profesional de 8 metros con doble escala métrica/pulgadas.' },
      { cat: 'hand-tools', name: 'Nivel de Burbuja 60cm', price: 6500, unit: 'unidad', emoji: '📐', desc: 'Nivel de burbuja de aluminio de 60cm con 3 viales. Precisión profesional.' },
      { cat: 'hand-tools', name: 'Nivel de Burbuja 120cm', price: 10800, unit: 'unidad', emoji: '📐', desc: 'Nivel de aluminio de 120cm con viales reforzados. Ideal para obras y construcción.' },
      { cat: 'hand-tools', name: 'Llave Inglesa 10"', price: 9500, unit: 'unidad', emoji: '🔧', desc: 'Llave inglesa ajustable con boca templada y mango antideslizante. Apertura hasta 30mm.' },
      { cat: 'hand-tools', name: 'Juego de Llaves Allen', price: 4800, unit: 'x9 u.', emoji: '🔧', desc: 'Set de llaves Allen milimétricas de 1.5 a 10mm. Acero al cromo vanadio con estuche.' },
      { cat: 'power-tools', name: 'Taladro Percutor 650W', price: 45900, unit: 'unidad', emoji: '🔌', desc: 'Taladro percutor con velocidad variable, mandril autocargable y empuñadura auxiliar.' },
      { cat: 'power-tools', name: 'Taladro Inalámbrico 12V', price: 38900, unit: 'unidad', emoji: '🪫', desc: 'Taladro inalámbrico con batería de 12V, cargador rápido y maletín de transporte.' },
      { cat: 'power-tools', name: 'Amoladora Angular 4½"', price: 38900, unit: 'unidad', emoji: '⚡', desc: 'Amoladora angular potente con protección de sobrecarga y disco de corte incluido.' },
      { cat: 'power-tools', name: 'Amoladora Angular 7"', price: 52900, unit: 'unidad', emoji: '⚡', desc: 'Amoladora angular profesional de 7 pulgadas con empuñadura lateral y guarda regulable.' },
      { cat: 'power-tools', name: 'Atornillador Inalámbrico', price: 29900, unit: 'unidad', emoji: '🪫', desc: 'Atornillador inalámbrico a batería con cargador rápido y maletín de transporte.' },
      { cat: 'power-tools', name: 'Caladora Eléctrica 500W', price: 28500, unit: 'unidad', emoji: '🔪', desc: 'Caladora con velocidad variable, corte orbital y guía láser para cortes precisos.' },
      { cat: 'power-tools', name: 'Lijadora Orbital 300W', price: 25900, unit: 'unidad', emoji: '🪵', desc: 'Lijadora orbital con sistema de extracción de polvo y velcro para cambios rápidos de lija.' },
      { cat: 'power-tools', name: 'Hidrolavadora 120bar', price: 45900, unit: 'unidad', emoji: '💦', desc: 'Hidrolavadora de 120 bares con manguera de 8m, lanza regulable y boquilla turbo.' },
      { cat: 'paint', name: 'Látex Interior 20L Blanco', price: 32500, unit: '20L', emoji: '🎨', desc: 'Látex interior mate premium. Cubritivo, lavable y de bajo olor. Color blanco nieve.' },
      { cat: 'paint', name: 'Látex Interior 4L Blanco', price: 8500, unit: '4L', emoji: '🎨', desc: 'Látex interior mate con alto poder cubritivo. Ideal para paredes y techos.' },
      { cat: 'paint', name: 'Esmalte Sintético 1L Blanco', price: 8500, unit: '1L', emoji: '🎨', desc: 'Esmalte sintético brillante para interiores y exteriores. Secado rápido y alta resistencia.' },
      { cat: 'paint', name: 'Esmalte Sintético 1L Negro', price: 8500, unit: '1L', emoji: '🎨', desc: 'Esmalte sintético brillante color negro. Ideal para rejas, muebles y herrería en general.' },
      { cat: 'paint', name: 'Barniz Marino 1L', price: 12500, unit: '1L', emoji: '🎨', desc: 'Barniz marino transparente con filtro UV. Protege maderas a la intemperie.' },
      { cat: 'paint', name: 'Enduido Plástico 1kg', price: 4500, unit: 'kg', emoji: '🧴', desc: 'Enduido plástico para paredes. Secado rápido, fácil de lijar. Ideal para interiores.' },
      { cat: 'paint', name: 'Rodillo Profesional 23cm', price: 3200, unit: 'unidad', emoji: '🖌️', desc: 'Rodillo de felpa profesional 23cm con mango telescópico. Para pintar superficies lisas.' },
      { cat: 'plumbing', name: 'Caño PVC ½" x 3m', price: 5200, unit: '3m', emoji: '🔩', desc: 'Caño de PVC sanitario de ½ pulgada. Resistente, liviano y fácil de instalar.' },
      { cat: 'plumbing', name: 'Caño PVC 1" x 3m', price: 7800, unit: '3m', emoji: '🔩', desc: 'Caño de PVC sanitario de 1 pulgada para instalaciones de mayor caudal.' },
      { cat: 'plumbing', name: 'Llave de Paso ½"', price: 6800, unit: 'unidad', emoji: '🔧', desc: 'Llave de paso esférica de ½ pulgada con cierre hermético y manija de aluminio.' },
      { cat: 'plumbing', name: 'Llave de Paso ¾"', price: 8200, unit: 'unidad', emoji: '🔧', desc: 'Llave de paso esférica de ¾ para instalaciones de agua corriente.' },
      { cat: 'plumbing', name: 'Codo PVC ½" x45°', price: 600, unit: 'unidad', emoji: '🔩', desc: 'Codo de PVC sanitario de ½ pulgada a 45 grados. Para desagües y ventilaciones.' },
      { cat: 'plumbing', name: 'Adaptador PVC ½"', price: 400, unit: 'unidad', emoji: '🔩', desc: 'Adaptador de PVC hembra-macho de ½ pulgada. Conexión rápida y segura.' },
      { cat: 'plumbing', name: 'Teflón 18mts', price: 1200, unit: 'unidad', emoji: '🧵', desc: 'Cinta de teflón para sellado de roscas. 18 metros de largo, uso sanitario y gas.' },
      { cat: 'plumbing', name: 'Sifón PVC 1¼"', price: 3500, unit: 'unidad', emoji: '🔩', desc: 'Sifón de PVC para bacha de cocina con salida a 1¼ pulgada. Incluye juntas.' },
      { cat: 'hardware', name: 'Bulones Allen M8 x30', price: 1500, unit: 'x10 u.', emoji: '⚙️', desc: 'Bulones Allen M8 x30mm en acero inoxidable. Incluye tuerca y arandela. x10 unidades.' },
      { cat: 'hardware', name: 'Tornillos Madera 4"', price: 2200, unit: 'x20 u.', emoji: '⚙️', desc: 'Tornillos para madera de 4 pulgadas con cabeza fresada. Acero galvanizado. x20 unidades.' },
      { cat: 'hardware', name: 'Tarugos N°8 x25', price: 800, unit: 'x12 u.', emoji: '⚙️', desc: 'Tarugos de expansión N°8 con tornillos incluidos. Ideal para paredes de ladrillo y hormigón.' },
      { cat: 'hardware', name: 'Arandelas Planas M8', price: 400, unit: 'x20 u.', emoji: '⭕', desc: 'Arandelas planas M8 en acero inoxidable. x20 unidades.' },
      { cat: 'hardware', name: 'Gancho Tornillo 6mm', price: 900, unit: 'x5 u.', emoji: '🪝', desc: 'Gancho con rosca de 6mm para colgar cuadros, estantes y decoración. x5 unidades.' },
      { cat: 'garden', name: 'Manguera Jardín 15m', price: 12500, unit: '15m', emoji: '🌿', desc: 'Manguera de PVC reforzado de 15 metros con acoples plásticos. Resistente a rayos UV.' },
      { cat: 'garden', name: 'Pulverizador 2L', price: 5800, unit: 'unidad', emoji: '🌿', desc: 'Pulverizador manual de 2 litros con boquilla regulable. Ideal para regar y fumigar.' },
      { cat: 'garden', name: 'Tijera de Podar 8"', price: 7900, unit: 'unidad', emoji: '✂️', desc: 'Tijera de podar con hojas de acero templado y mango ergonómico. Corte limpio y preciso.' },
      { cat: 'garden', name: 'Rastrillo Metálico 30cm', price: 5200, unit: 'unidad', emoji: '🌿', desc: 'Rastrillo de acero con mango de madera de 30cm. Ideal para jardinería y limpieza.' },
      { cat: 'garden', name: 'Guantes Jardinería', price: 3800, unit: 'par', emoji: '🧤', desc: 'Guantes de jardinería con palma de látex antideslizante. Protegen espinas y humedad.' },
    ],
    combos: [
      { name: 'Kit Básico Herramientas', desc: 'Martillo + Pinza + Destornillador + Cinta métrica', emoji: '🔧🛠️', price: 21900, products: ['Martillo de Carpintero 500g', 'Pinza Universal 8"', 'Destornillador Plano 6mm', 'Cinta Métrica 5m'] },
      { name: 'Combo Pintor', desc: 'Látex 20L + Rodillo + Bandeja + Cinta de enmascarar', emoji: '🎨🖌️', price: 38900, products: ['Látex Interior 20L Blanco', 'Rodillo Profesional 23cm'] },
    ],
  },
  verduleria: {
    categories: [
      { name: 'Frutas', slug: 'frutas', icon: '🍎', sort_order: 1 },
      { name: 'Verduras', slug: 'verduras', icon: '🥬', sort_order: 2 },
      { name: 'Huevos y Lácteos', slug: 'huevos', icon: '🥚', sort_order: 3 },
      { name: 'Almacén', slug: 'almacen', icon: '📦', sort_order: 4 },
    ],
    products: [
      { cat: 'frutas', name: 'Manzana Red Delicious', price: 1200, unit: 'kg', emoji: '🍎', desc: 'Manzana roja dulce y jugosa, perfecta para comer fresca o en ensaladas de fruta.' },
      { cat: 'frutas', name: 'Banana Ecuatoriana', price: 1400, unit: 'kg', emoji: '🍌', desc: 'Banana ecuatoriana de primera calidad, dulce y cremosa. Ideal para postres.' },
      { cat: 'frutas', name: 'Naranja Jugo', price: 900, unit: 'kg', emoji: '🍊', desc: 'Naranja jugosa y dulce, perfecta para exprimir. Rica en vitamina C.' },
      { cat: 'frutas', name: 'Frutilla', price: 3200, unit: 'kg', emoji: '🍓', desc: 'Frutillas frescas y dulces, seleccionadas a mano. Ideales para postres y ensaladas.' },
      { cat: 'verduras', name: 'Lechuga Fresca', price: 1100, unit: 'kg', emoji: '🥬', desc: 'Lechuga criolla fresca, cosechada del día. Crujiente y llena de sabor.' },
      { cat: 'verduras', name: 'Tomate Perita', price: 1800, unit: 'kg', emoji: '🍅', desc: 'Tomate perita maduro, ideal para ensaladas y salsas. Sabor natural intenso.' },
      { cat: 'verduras', name: 'Cebolla', price: 800, unit: 'kg', emoji: '🧅', desc: 'Cebolla blanca de primera calidad. Ideal para guisos, ensaladas y condimentos.' },
      { cat: 'verduras', name: 'Papa', price: 700, unit: 'kg', emoji: '🥔', desc: 'Papa fresca seleccionada. Perfecta para puré, frituras y guisos.' },
      { cat: 'huevos', name: 'Huevos Blancos x6', price: 3200, unit: 'x6 u.', emoji: '🥚', desc: 'Huevos blancos frescos de gallinas libres. Categoría A, x6 unidades.' },
      { cat: 'huevos', name: 'Leche Entera 1L', price: 1800, unit: '1L', emoji: '🥛', desc: 'Leche entera pasteurizada de primera calidad. Cremosa y nutritiva.' },
      { cat: 'almacen', name: 'Arroz 1kg', price: 2200, unit: 'kg', emoji: '📦', desc: 'Arroz largo fino, de grano perfecto. Ideal para guarniciones y ensaladas.' },
    ],
    combos: [
      { name: 'Bolsa de Frutas', desc: '5kg de frutas variadas de estación', emoji: '🍎🍊', price: 8900, products: ['Manzana Red Delicious', 'Banana Ecuatoriana', 'Naranja Jugo', 'Frutilla'] },
      { name: 'Canasta Verde', desc: '7kg de verduras seleccionadas', emoji: '🥬🥕', price: 7500, products: ['Lechuga Fresca', 'Tomate Perita', 'Cebolla', 'Papa'] },
    ],
  },
  carniceria: {
    categories: [
      { name: 'Carnes Vacunas', slug: 'vacunos', icon: '🥩', sort_order: 1 },
      { name: 'Cerdos', slug: 'cerdo', icon: '🐷', sort_order: 2 },
      { name: 'Pollos', slug: 'pollo', icon: '🍗', sort_order: 3 },
      { name: 'Embutidos', slug: 'embutidos', icon: '🌭', sort_order: 4 },
      { name: 'Preparados', slug: 'preparados', icon: '🍖', sort_order: 5 },
    ],
    products: [
      { cat: 'vacunos', name: 'Asado de Tira', price: 8500, unit: 'kg', emoji: '🥩', desc: 'Asado de tira criollo, carne tierna con el punto justo de grasa. Ideal para parrilla.' },
      { cat: 'vacunos', name: 'Bife de Chorizo', price: 9500, unit: 'kg', emoji: '🥩', desc: 'Bife de chorizo premium de 2cm de espesor. Marmolado y jugoso.' },
      { cat: 'vacunos', name: 'Cuadril', price: 7800, unit: 'kg', emoji: '🥩', desc: 'Cuadril entero sin hueso. Ideal para horno, bifes o milanesas.' },
      { cat: 'vacunos', name: 'Carne Picada Especial', price: 5500, unit: 'kg', emoji: '🥩', desc: 'Carne picada de nalga con el punto justo de grasa. Para pastas y hamburguesas.' },
      { cat: 'vacunos', name: 'Matambre Arrollado', price: 7200, unit: 'kg', emoji: '🥩', desc: 'Matambre arrollado cocido, relleno con verduras y especias. Listo para servir.' },
      { cat: 'vacunos', name: 'Osobuco', price: 4800, unit: 'kg', emoji: '🦴', desc: 'Osobuco cortado en rodajas de 3cm. Ideal para guisos y cocciones lentas.' },
      { cat: 'cerdo', name: 'Cerdo a la Pizza', price: 5200, unit: 'kg', emoji: '🐷', desc: 'Bondiola de cerdo fileteada para pizza. Sabor suave y textura tierna.' },
      { cat: 'cerdo', name: 'Costillas de Cerdo', price: 4900, unit: 'kg', emoji: '🐷', desc: 'Costillas de cerdo ahumadas con salsa barbacoa. Ideal para parrilla.' },
      { cat: 'cerdo', name: 'Pechito de Cerdo', price: 5800, unit: 'kg', emoji: '🐷', desc: 'Pechito de cerdo deshuesado con cuero crocante. Ideal para hornear.' },
      { cat: 'cerdo', name: 'Chorizo Colorado', price: 4200, unit: 'kg', emoji: '🌭', desc: 'Chorizo colorado artesanal con pimentón ahumado.' },
      { cat: 'pollo', name: 'Pollo Entero', price: 3800, unit: 'unidad', emoji: '🍗', desc: 'Pollo fresco de campo entero, aproximadamente 2.5kg. Ideal para horno.' },
      { cat: 'pollo', name: 'Pata Muslo', price: 2900, unit: 'kg', emoji: '🍗', desc: 'Pata muslo de pollo fresca, jugosa y sabrosa. Ideal para parrilla.' },
      { cat: 'pollo', name: 'Pechuga de Pollo', price: 5200, unit: 'kg', emoji: '🍗', desc: 'Pechuga de pollo deshuesada y sin piel. Carne magra y saludable.' },
      { cat: 'pollo', name: 'Alitas de Pollo', price: 2400, unit: 'kg', emoji: '🪽', desc: 'Alitas de pollo frescas. Perfectas para hornear o freír con salsa.' },
      { cat: 'embutidos', name: 'Chorizo Parrillero', price: 3800, unit: 'kg', emoji: '🌭', desc: 'Chorizo parrillero artesanal de cerdo y vacuno con condimentos tradicionales.' },
      { cat: 'embutidos', name: 'Morcilla', price: 3200, unit: 'kg', emoji: '🫘', desc: 'Morcilla criolla con arroz y especias. Ideal para picada y parrilla.' },
      { cat: 'embutidos', name: 'Salchicha Parrillera', price: 2800, unit: 'kg', emoji: '🌭', desc: 'Salchicha parrillera de cerdo, ahumada y con sabor intenso.' },
      { cat: 'preparados', name: 'Hamburguesas Caseras x4', price: 6800, unit: 'x4 u.', emoji: '🍔', desc: 'Hamburguesas caseras de carne vacuna premium, x4 unidades de 150g cada una.' },
      { cat: 'preparados', name: 'Milanesa de Carne x2', price: 4200, unit: 'x2 u.', emoji: '🍖', desc: 'Milanesas de nalga empanadas artesanalmente. x2 unidades listas para freír.' },
      { cat: 'preparados', name: 'Brochette de Pollo x6', price: 5500, unit: 'x6 u.', emoji: '🍢', desc: 'Brochettes de pollo con pimiento y cebolla, x6 unidades. Listas para la parrilla.' },
    ],
    combos: [
      { name: 'Combo Parrillero x4', desc: '2kg Asado + 1kg Chorizo + 1kg Morcilla', emoji: '🥩🌭', price: 24500, products: ['Asado de Tira', 'Chorizo Parrillero', 'Morcilla'] },
      { name: 'Combo Hamburguesas', desc: '12 Hamburguesas + 12 panes + Cheddar 250g', emoji: '🍔🧀', price: 18900, products: ['Hamburguesas Caseras x4'] },
    ],
  },
  panaderia: {
    categories: [
      { name: 'Panes', slug: 'panes', icon: '🍞', sort_order: 1 },
      { name: 'Facturas', slug: 'facturas', icon: '🥐', sort_order: 2 },
      { name: 'Pastelería', slug: 'pasteleria', icon: '🎂', sort_order: 3 },
      { name: 'Salados', slug: 'salados', icon: '🥟', sort_order: 4 },
      { name: 'Galletas', slug: 'galletas', icon: '🍪', sort_order: 5 },
    ],
    products: [
      { cat: 'panes', name: 'Pan Francés', price: 1200, unit: 'kg', emoji: '🍞', desc: 'Pan francés artesanal horneado diariamente. Corteza crocante y miga esponjosa.' },
      { cat: 'panes', name: 'Pan de Campo', price: 1800, unit: 'unidad', emoji: '🍞', desc: 'Pan de campo redondo de 500g. Masa madre natural, sabor casero.' },
      { cat: 'panes', name: 'Pan Integral', price: 2200, unit: 'unidad', emoji: '🍞', desc: 'Pan integral con semillas de chía, lino y girasol. Saludable y delicioso.' },
      { cat: 'panes', name: 'Pan de Hamburguesa x4', price: 2500, unit: 'x4 u.', emoji: '🍔', desc: 'Pan de hamburguesa artesanal x4 unidades. Suave y liviano.' },
      { cat: 'facturas', name: 'Medialuna de Manteca', price: 3500, unit: 'kg', emoji: '🥐', desc: 'Medialunas de manteca artesanales, hojaldradas y dulces. Aprox. 12 unidades por kg.' },
      { cat: 'facturas', name: 'Facturas Variadas', price: 3800, unit: 'kg', emoji: '🥐', desc: 'Facturas surtidas: vigilantes, cañoncitos, boyos y más. Aprox. 10 unidades por kg.' },
      { cat: 'facturas', name: 'Churros de Crema', price: 2800, unit: 'x6 u.', emoji: '🫘', desc: 'Churros rellenos de crema pastelera, espolvoreados con azúcar. x6 unidades.' },
      { cat: 'pasteleria', name: 'Torta Rogel', price: 9500, unit: 'unidad', emoji: '🎂', desc: 'Torta Rogel con dulce de leche y merengue. 12 capas, 2kg. Rinde 12 porciones.' },
      { cat: 'pasteleria', name: 'Lemon Pie', price: 6800, unit: 'unidad', emoji: '🥧', desc: 'Lemon Pie con base de masa brisée, crema de limón y merengue italiano.' },
      { cat: 'pasteleria', name: 'Alfajores de Maicena x6', price: 4200, unit: 'x6 u.', emoji: '🍪', desc: 'Alfajores de maicena rellenos de dulce de leche y coco rallado. x6 unidades.' },
      { cat: 'salados', name: 'Empanada de Carne', price: 1500, unit: 'unidad', emoji: '🥟', desc: 'Empanada de carne cortada a cuchillo con huevo, aceitunas y pasas.' },
      { cat: 'salados', name: 'Empanada de Jamón y Queso', price: 1400, unit: 'unidad', emoji: '🥟', desc: 'Empanada de jamón cocido y queso cremoso fundente.' },
      { cat: 'salados', name: 'Tapa de Empanadas x24', price: 3500, unit: 'x24 u.', emoji: '🥟', desc: 'Tapas de empanadas de hojaldre para horno. x24 unidades.' },
      { cat: 'galletas', name: 'Galletas de Avena', price: 2800, unit: 'kg', emoji: '🍪', desc: 'Galletas de avena con pasas de uva. Saludables y caseras.' },
      { cat: 'galletas', name: 'Galletitas de Manteca', price: 3200, unit: 'kg', emoji: '🍪', desc: 'Galletitas de manteca clásicas, bañadas en chocolate. Ideales para la merienda.' },
    ],
    combos: [
      { name: 'Desayuno x2', desc: '2 Medialunas + Café + Jugo de naranja', emoji: '🥐☕', price: 6500, products: ['Medialuna de Manteca', 'Pan de Hamburguesa x4'] },
      { name: 'Combo Merienda', desc: 'Torta Rogel + 6 Alfajores + 1kg Facturas', emoji: '🎂🥐', price: 16500, products: ['Torta Rogel', 'Alfajores de Maicena x6', 'Facturas Variadas'] },
    ],
  },
  libreria: {
    categories: [
      { name: 'Útiles Escolares', slug: 'escolar', icon: '✏️', sort_order: 1 },
      { name: 'Art. de Oficina', slug: 'oficina', icon: '📎', sort_order: 2 },
      { name: 'Bellas Artes', slug: 'arte', icon: '🎨', sort_order: 3 },
      { name: 'Libros', slug: 'libros', icon: '📚', sort_order: 4 },
      { name: 'Mochilas', slug: 'mochilas', icon: '🎒', sort_order: 5 },
    ],
    products: [
      { cat: 'escolar', name: 'Cuaderno Rayado A4 x48', price: 3200, unit: 'unidad', emoji: '📓', desc: 'Cuaderno rayado A4 tapa dura, 48 hojas. Ideal para el colegio.' },
      { cat: 'escolar', name: 'Lapicera Azul Bic', price: 400, unit: 'unidad', emoji: '🖊️', desc: 'Lapicera azul Bic cristal. Punta fina, escritura suave.' },
      { cat: 'escolar', name: 'Lápiz Negro HB', price: 300, unit: 'unidad', emoji: '✏️', desc: 'Lápiz negro HB N°2 con goma. Para dibujo y escritura.' },
      { cat: 'escolar', name: 'Goma de Borrar', price: 350, unit: 'unidad', emoji: '🧹', desc: 'Goma de borrar blanca suave. No mancha ni daña el papel.' },
      { cat: 'escolar', name: 'Regla 30cm', price: 800, unit: 'unidad', emoji: '📏', desc: 'Regla de plástico transparente de 30cm con escala métrica.' },
      { cat: 'escolar', name: 'Mochila Escolar', price: 18900, unit: 'unidad', emoji: '🎒', desc: 'Mochila escolar con compartimento para notebook. Resistente y ergonómica.' },
      { cat: 'oficina', name: 'Resma A4 500hs', price: 6500, unit: 'unidad', emoji: '📄', desc: 'Resma de papel A4 75g/m², 500 hojas. Ideal para impresoras láser e inkjet.' },
      { cat: 'oficina', name: 'Carpeta Archivadora', price: 2200, unit: 'unidad', emoji: '📁', desc: 'Carpeta archivadora A4 lomo ancho 8cm con gancho metálico.' },
      { cat: 'oficina', name: 'Marcador Permanente Negro', price: 1200, unit: 'unidad', emoji: '🖍️', desc: 'Marcador permanente punta biselada. Resistente al agua y la luz solar.' },
      { cat: 'oficina', name: 'Notas Adhesivas 76x76', price: 1500, unit: 'bloque', emoji: '📋', desc: 'Bloque de notas adhesivas post-it 76x76mm, 100 hojas. 5 colores.' },
      { cat: 'arte', name: 'Acuarelas x12 colores', price: 8500, unit: 'estuche', emoji: '🎨', desc: 'Estuche de acuarelas profesionales x12 colores vibrantes. Incluye pincel.' },
      { cat: 'arte', name: 'Lápices de Color x24', price: 7200, unit: 'estuche', emoji: '🖍️', desc: 'Lápices de colores x24 unidades con mina suave y pigmentos intensos.' },
      { cat: 'arte', name: 'Block Dibujo A4', price: 3800, unit: 'unidad', emoji: '📝', desc: 'Block de dibujo A4 con 50 hojas de papel obra 120g. Ideal para lápiz y carbonilla.' },
      { cat: 'libros', name: 'Cien Años de Soledad', price: 18900, unit: 'unidad', emoji: '📖', desc: 'Gabriel García Márquez — Edición conmemorativa de la obra maestra del realismo mágico.' },
      { cat: 'libros', name: 'El Principito', price: 8500, unit: 'unidad', emoji: '📘', desc: 'Antoine de Saint-Exupéry — Edición ilustrada a color. Un clásico imprescindible.' },
      { cat: 'libros', name: 'Libreta Rayada A5', price: 2500, unit: 'unidad', emoji: '📓', desc: 'Libreta rayada A5 tapa flexible, 80 hojas. Ideal para notas diarias.' },
      { cat: 'mochilas', name: 'Mochila Notebook 15.6"', price: 22500, unit: 'unidad', emoji: '🎒', desc: 'Mochila acolchada para notebook de 15.6 pulgadas. Varios compartimentos.' },
      { cat: 'mochilas', name: 'Cartuchera Estuche', price: 4500, unit: 'unidad', emoji: '👝', desc: 'Cartuchera estuche con cierre, capacidad para 40 lápices. Tela resistente.' },
      { cat: 'mochilas', name: 'Bolso Matero', price: 8500, unit: 'unidad', emoji: '🧉', desc: 'Bolso matero térmico con soporte para termo y compartimento para yerba.' },
    ],
    combos: [
      { name: 'Kit Escolar Básico', desc: '5 Cuadernos + 10 Lapiceras + Regla + Goma + Mochila', emoji: '✏️📓', price: 28500, products: ['Cuaderno Rayado A4 x48', 'Lapicera Azul Bic', 'Regla 30cm', 'Goma de Borrar', 'Mochila Escolar'] },
      { name: 'Combo Arte', desc: 'Acuarelas x12 + Lápices x24 + Block A4 + 3 Pinceles', emoji: '🎨🖌️', price: 16500, products: ['Acuarelas x12 colores', 'Lápices de Color x24', 'Block Dibujo A4'] },
    ],
  },
  indumentaria: {
    categories: [
      { name: 'Remeras', slug: 'remeras', icon: '👕', sort_order: 1 },
      { name: 'Pantalones', slug: 'pantalones', icon: '👖', sort_order: 2 },
      { name: 'Buzos', slug: 'buzos', icon: '🧥', sort_order: 3 },
      { name: 'Accesorios', slug: 'accesorios', icon: '🧢', sort_order: 4 },
      { name: 'Zapatillas', slug: 'zapatillas', icon: '👟', sort_order: 5 },
    ],
    products: [
      { cat: 'remeras', name: 'Remera Algodón Lisa', price: 8500, unit: 'unidad', emoji: '👕', desc: 'Remera de algodón peinado 24.1, lisa. Corte recto, mangas cortas. Varios colores.' },
      { cat: 'remeras', name: 'Remera Estampada Urbana', price: 10500, unit: 'unidad', emoji: '👕', desc: 'Remera de algodón con estampado urbano. Diseño exclusivo, tela premium.' },
      { cat: 'remeras', name: 'Remera Manga Larga', price: 11500, unit: 'unidad', emoji: '👕', desc: 'Remera manga larga de algodón jersey. Ideal para invierno. Varios colores.' },
      { cat: 'remeras', name: 'Chomba Piqué', price: 13500, unit: 'unidad', emoji: '👕', desc: 'Chomba de piqué premium con cuello y botones. Corte clásico y elegante.' },
      { cat: 'pantalones', name: 'Jeans Clásico', price: 22500, unit: 'unidad', emoji: '👖', desc: 'Jeans de denim clásico 5 bolsillos. Algodón con elastano para mayor confort.' },
      { cat: 'pantalones', name: 'Jogging Algodón', price: 14500, unit: 'unidad', emoji: '👖', desc: 'Jogging de algodón frizado con cintura elástica y cordón. Bolsillos laterales.' },
      { cat: 'pantalones', name: 'Bermuda Jean', price: 12500, unit: 'unidad', emoji: '🩳', desc: 'Bermuda de jean clásico con dobladillo desflecado. Ideal para el verano.' },
      { cat: 'buzos', name: 'Buzo Canguro Algodón', price: 19500, unit: 'unidad', emoji: '🧥', desc: 'Buzo canguro de algodón frizado con capucha y bolsillo delantero.' },
      { cat: 'buzos', name: 'Buzo Polar', price: 16500, unit: 'unidad', emoji: '🧥', desc: 'Buzo polar térmico suave y liviano. Ideal para actividades al aire libre.' },
      { cat: 'buzos', name: 'Campera Rompevientos', price: 25900, unit: 'unidad', emoji: '🧥', desc: 'Campera rompevientos con capucha desmontable. Resistente al agua y al viento.' },
      { cat: 'accesorios', name: 'Gorra Premium', price: 8500, unit: 'unidad', emoji: '🧢', desc: 'Gorra premium con visera curva y cierre ajustable. Bordado de alta calidad.' },
      { cat: 'accesorios', name: 'Mochila Urbana', price: 18900, unit: 'unidad', emoji: '🎒', desc: 'Mochila urbana 25L con compartimento para notebook. Diseño minimalista.' },
      { cat: 'accesorios', name: 'Cinto Cuero', price: 9500, unit: 'unidad', emoji: '🔗', desc: 'Cinto de cuero vacuno con hebilla metálica. Ancho 35mm, varios colores.' },
      { cat: 'zapatillas', name: 'Zapatillas Urbanas', price: 35900, unit: 'par', emoji: '👟', desc: 'Zapatillas urbanas con suela amortiguada y capellada de mesh transpirable.' },
      { cat: 'zapatillas', name: 'Zapatillas Deportivas', price: 42500, unit: 'par', emoji: '👟', desc: 'Zapatillas deportivas con tecnología de retorno de energía. Ideales para running.' },
      { cat: 'zapatillas', name: 'Ojotas de Goma', price: 6500, unit: 'par', emoji: '🩴', desc: 'Ojotas de goma suave con plantilla anatómica. Cómodas y resistentes.' },
    ],
    combos: [
      { name: 'Combo Urbano', desc: 'Remera + Jogging + Gorra', emoji: '👕👖🧢', price: 35500, products: ['Remera Algodón Lisa', 'Jogging Algodón', 'Gorra Premium'] },
      { name: 'Look Full', desc: 'Buzo + Jean + Zapatillas + Mochila', emoji: '🧥👖👟🎒', price: 82500, products: ['Buzo Canguro Algodón', 'Jeans Clásico', 'Zapatillas Urbanas', 'Mochila Urbana'] },
    ],
  },
};
